# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

# Default values for application-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

org: open-cluster-management

global:
  pullPolicy: Always
  imageOverrides:
    application_ui: ""
  certificateAuthority:
    issuer: multicloud-ca-issuer
    kind: Issuer

hubconfig:
  nodeSelector: ""
  replicaCount: 1


affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 70
      podAffinityTerm:
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchExpressions:
          - key: ocm-antiaffinity-selector
            operator: In
            values:
            - applicationui
    - weight: 35
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: ocm-antiaffinity-selector
            operator: In
            values:
            - applicationui

pullSecret: null
arch:
- amd64
- ppc64le
- s390x

nodeSelector:
  enabled: false
  os: ""
  customLabelSelector: ""
  customLabelValue: ""

enabled: true
applicationui:
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
