# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# Copyright (c) 2020 Red Hat, Inc.

# Default values for application-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageShaDigests:
  application_ui: ""

standalone: false
pullSecret: null
imageTagPostfix: ""
arch:
- amd64
- ppc64le
- s390x

replicas: 1

nodeSelector:
  enabled: false
  os: ""
  customLabelSelector: ""
  customLabelValue: ""
cfcRouterUrl: "https://management-ingress:443"

enabled: true
applicationui:
  image:
    repository: quay.io/open-cluster-management
    name: application-ui
    tag: 3.5.0
    pullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
