# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# Copyright (c) 2020 Red Hat, Inc.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.open-cluster-management.io/auth-type: access-token
    ingress.open-cluster-management.io/secure-backends: 'true'
    kubernetes.io/ingress.class: ingress-open-cluster-management
  name: {{ template "application.fullname" . }}-applicationui
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "application.name" . }}
    helm.sh/chart: {{ template "application.chart" . }}
spec:
  rules:
  - http:
      paths:
      - path: /multicloud/applications
        backend:
          serviceName: {{ template "application.fullname" . }}-applicationui
          servicePort: 3001
