# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# Copyright (c) 2020 Red Hat, Inc.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "application.fullname" . }}-applicationui
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    component: "applicationui"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "application.name" . }}
    helm.sh/chart: {{ template "application.chart" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "application.name" . }}
      component: "applicationui"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "application.name" . }}
        component: "applicationui"
        release: {{ .Release.Name }}
        chart: {{ template "application.chart" . }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ template "application.name" . }}
        helm.sh/chart: {{ template "application.chart" . }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default  
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.arch }}
                - {{ . }}
                {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - applicationui
              topologyKey: failure-domain.beta.kubernetes.io/zone
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
      containers:
      - name: application-ui
        image: {{ .Values.global.imageOverrides.application_ui }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        resources:
        {{- toYaml .Values.applicationui.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        env:
        - name: ICP_STANDALONE
          value: "{{ .Values.standalone }}"
        - name: hcmUiApiUrl
          value: https://console-api:4000/hcmuiapi
        - name: searchApiUrl
          value: https://search-search-api:4010/searchapi
        - name: cfcRouterUrl
          value: {{ .Values.cfcRouterUrl }}
        - name: leftNav
          value: {{ .Release.Name }}-nav
        - name: PLATFORM_IDENTITY_PROVIDER_URL
          value: {{ .Values.cfcRouterUrl }}/idprovider
        ports:
        - containerPort: 3001
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livenessProbe
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readinessProbe
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      {{- if .Values.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      {{- end }}
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
      {{- if .Values.nodeSelector.os }}
        "beta.kubernetes.io/os" : {{ .Values.nodeSelector.os }}
      {{- end }}
      {{- if .Values.nodeSelector.customLabelSelector }}
        {{ .Values.nodeSelector.customLabelSelector }} : {{ .Values.nodeSelector.customLabelValue}}
      {{- end }}
      {{- end }}
