# Copyright (c) 2020 Red Hat, Inc.

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "application.fullname" . }}-applicationui-ca-cert
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
    component: "applicationui"
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ template "application.fullname" . }}-applicationui-secrets
  issuerRef:
    name: {{ .Values.global.certificateAuthority.issuer }}
    kind: {{ .Values.global.certificateAuthority.kind }}
  commonName: applicationui
  organization:
  - Red Hat